# Generated by Django 3.2.15 on 2023-01-17 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_addressbook_user'),
        ('store', '0002_remove_order_driver'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, choices=[('EAST', 'EAST'), ('WEST', 'WEST'), ('SOUTH', 'SOUTH'), ('NORTH', 'NORTH'), ('REGINE', 'REGINE'), ('GOMAPS', 'GOMAPS')], max_length=10, null=True)),
                ('note', models.TextField(blank=True)),
                ('is_status', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.addressbook')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
