# Generated by Django 3.2.15 on 2023-01-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20230117_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='order',
        ),
    ]
