# Generated by Django 3.2.15 on 2023-02-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20230117_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='region',
            field=models.CharField(blank=True, choices=[('EAST', '동부'), ('WEST', '서부'), ('SOUTH', '남부'), ('NORTH', '북부'), ('REGINE', '외곽'), ('GOMAPS', '고맙스')], max_length=10, null=True),
        ),
    ]
