# Generated by Django 3.2.15 on 2023-02-03 01:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20230129_2125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0004_alter_driver_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver',
            new_name='StaffMember',
        ),
    ]
