# Generated by Django 3.2.15 on 2023-02-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_rename_driver_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='position',
            field=models.CharField(blank=True, choices=[('부장', '부장'), ('차장', '차장'), ('대리', '대리')], max_length=30, null=True),
        ),
    ]
