# Generated by Django 3.2.15 on 2023-02-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_staffmember_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='note',
        ),
    ]
