# Generated by Django 3.2.15 on 2023-02-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_remove_staffmember_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='position',
            field=models.CharField(blank=True, choices=[('팀장', '팀장'), ('차장', '차장'), ('과장', '과장'), ('대리', '대리')], max_length=30, null=True),
        ),
    ]
