# Generated by Django 3.2.15 on 2023-02-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_staffmember_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='region',
            field=models.CharField(blank=True, choices=[('동부팀', '동부팀'), ('서부팀', '서부팀'), ('남부팀', '남부팀'), ('북부팀', '북부팀'), ('외곽팀', '외곽팀'), ('고맙스', '고맙스')], max_length=10, null=True),
        ),
    ]
