# Generated by Django 3.2.15 on 2023-03-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_order_delivery_photo'),
        ('delivery', '0009_alter_staffmember_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.staffmember')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderitem')),
            ],
        ),
    ]
