# Generated by Django 3.2.15 on 2023-03-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_deliverystatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverystatus',
            old_name='order_status',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='deliverystatus',
            old_name='order_staff',
            new_name='staffs',
        ),
    ]
