# Generated by Django 3.2.15 on 2023-03-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20230310_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverystatus',
            old_name='orders',
            new_name='delivery_order',
        ),
        migrations.RenameField(
            model_name='deliverystatus',
            old_name='staffs',
            new_name='delivery_staffs',
        ),
    ]
