# Generated by Django 3.2.15 on 2023-03-10 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20230310_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
