# Generated by Django 3.2.15 on 2023-03-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_order_delivery_photo'),
        ('delivery', '0013_auto_20230310_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
