# Generated by Django 3.2.15 on 2022-12-25 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True, verbose_name='Title')),
                ('e_title', models.CharField(max_length=100, null=True, verbose_name='e_title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, default='images/category/default.png', upload_to='images/category', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_e_name', models.CharField(blank=True, max_length=150, null=True)),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('NSW', 'NSW'), ('VIC', 'VIC'), ('QLD', 'QLD'), ('ACT', 'ACT'), ('SA', 'SA'), ('WA', 'WA'), ('NT', 'NT'), ('TAS', 'TAS')], default='NSW', max_length=3)),
                ('postcode', models.CharField(max_length=4)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=150)),
                ('message', models.TextField(blank=True, null=True)),
                ('tracking_no', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode_img', models.ImageField(blank=True, upload_to='order/barcode/')),
                ('ami_file', models.FileField(blank=True, upload_to='order/ami/')),
                ('order_pdf', models.FileField(blank=True, upload_to='order/pdf/')),
                ('delivery_note', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_driver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('e_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='English Title')),
                ('bar_code', models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='BAR Code')),
                ('location', models.CharField(blank=True, max_length=6, null=True, verbose_name='Location')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='List Price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit')),
                ('spec', models.CharField(blank=True, max_length=20, null=True, verbose_name='Spec')),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Color')),
                ('per_box', models.IntegerField(blank=True, null=True, verbose_name='Per Box')),
                ('tag', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tag')),
                ('image', models.ImageField(blank=True, default='images/product/default.png', upload_to='images/product', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['location'],
                'index_together': {('id', 'title')},
            },
        ),
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order_code', models.CharField(blank=True, max_length=6, null=True)),
                ('order_type', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='OrderCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('order_type', models.CharField(choices=[('일반', '일반'), ('야채', '야채'), ('주류', '주류')], default='일반', max_length=10)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.addressbook')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_code', models.CharField(blank=True, max_length=6, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
