# Generated by Django 3.2.15 on 2023-01-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rep_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='rep_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
