# Generated by Django 3.2.15 on 2023-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230117_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='BAR Code'),
        ),
    ]
