# Generated by Django 3.2.15 on 2023-01-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(blank=True, choices=[('정상', '정상'), ('파손', '파손'), ('반품', '반품'), ('미배달', '미배달')], default='정상', max_length=100, null=True),
        ),
    ]
