# Generated by Django 3.2.15 on 2023-02-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_ami_daily_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ami_daily_file',
        ),
    ]
