# Generated by Django 3.2.15 on 2023-02-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_ami_daily_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ami_daily_file',
            field=models.FileField(blank=True, upload_to='order/daily/'),
        ),
    ]
