# Generated by Django 3.2.15 on 2023-02-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_ami_daily_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ami_file',
            field=models.FileField(blank=True, upload_to='order/ami/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='barcode_img',
            field=models.ImageField(blank=True, upload_to='order/barcode/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_pdf',
            field=models.FileField(blank=True, upload_to='order/pdf/%Y/%m/%d/'),
        ),
    ]
