# Generated by Django 3.2.15 on 2023-03-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230223_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='amiDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_merged', models.FileField(blank=True, upload_to='order/barcode/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
