# Generated by Django 3.2.15 on 2023-03-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_amidaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amidaily',
            name='daily_merged',
            field=models.FileField(blank=True, upload_to='order/daily/%Y/%m/%d/'),
        ),
    ]
