# Generated by Django 3.2.15 on 2023-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20230305_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyjobs',
            name='daily_merged_csv',
            field=models.FileField(blank=True, upload_to='order/daily/csv/%Y/%m/%d/'),
        ),
    ]
