# Generated by Django 3.2.15 on 2023-03-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_dailyjobs_daily_merged_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_daily_file',
            field=models.FileField(blank=True, upload_to='order/daily'),
        ),
    ]
