# Generated by Django 3.2.15 on 2023-03-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_pdf_daily_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyjobs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='dailyjobs',
            name='daily_merged_csv',
            field=models.FileField(blank=True, upload_to='order/daily/csv/%Y/%m/%d/', verbose_name='알맹이CSV'),
        ),
        migrations.AlterField(
            model_name='dailyjobs',
            name='daily_merged_pdf',
            field=models.FileField(blank=True, upload_to='order/daily/pdf/%Y/%m/%d', verbose_name='주문서PDF'),
        ),
    ]
