# Generated by Django 3.2.15 on 2023-03-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20230307_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('미수금', '미수금'), ('현금완납', '현금완납')], max_length=150, null=True),
        ),
    ]
