# Generated by Django 3.2.15 on 2023-03-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('수금', '수금'), ('미수금', '미수금')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(blank=True, choices=[('정상', '정상'), ('반품', '반품'), ('미배달', '미배달')], default='정상', max_length=100, null=True),
        ),
    ]
