# Generated by Django 3.2.15 on 2023-03-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20230307_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_photo',
            field=models.ImageField(null=True, upload_to='order/delivery/%Y/%m/%d'),
        ),
    ]
