# Generated by Django 3.2.15 on 2023-03-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_order_delivery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_photo',
            field=models.ImageField(blank=True, default=1, upload_to='order/delivery/%Y/%m/%d', verbose_name='사진업로드'),
            preserve_default=False,
        ),
    ]
