# Generated by Django 3.2.15 on 2023-03-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_order_delivery_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='representative',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rep_first_name',
            new_name='driver_first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rep_last_name',
            new_name='driver_last_name',
        ),
    ]
