# Generated by Django 3.2.15 on 2023-03-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20230308_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_photo',
            field=models.ImageField(blank=True, upload_to='order/delivery/%Y/%m/%d', verbose_name='첨부사진'),
        ),
    ]
