# Generated by Django 3.2.15 on 2023-03-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_alter_deliverystatus_delivery_order'),
        ('store', '0026_alter_order_delivery_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.staffmember'),
            preserve_default=False,
        ),
    ]
