# Generated by Django 3.2.15 on 2023-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_order_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_team',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
