# Generated by Django 3.2.15 on 2023-02-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('DRIVER', 'Driver'), ('CUSTOMER', 'Customer')], default=None, max_length=10, null=True),
        ),
    ]
