# Generated by Django 3.2.15 on 2023-01-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeman', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyJobs',
        ),
    ]
