# Generated by Django 3.2.15 on 2023-01-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('storeman', '0003_createuserorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuserorder',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.delivery'),
        ),
    ]
