# Generated by Django 3.2.15 on 2023-01-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeman', '0004_createuserorder_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuserorder',
            name='order_code',
        ),
        migrations.RemoveField(
            model_name='createuserorder',
            name='product',
        ),
    ]
