# Generated by Django 3.2.15 on 2023-01-17 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_addressbook_representative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeman', '0007_remove_createuserorder_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUserOrder',
            new_name='UserOrder',
        ),
    ]
