# Generated by Django 3.2.15 on 2023-01-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeman', '0008_rename_createuserorder_userorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorderitem',
            name='order_code',
        ),
    ]
