# Generated by Django 3.2.15 on 2023-02-03 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_driver_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeman', '0009_remove_userorderitem_order_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drv_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver')),
                ('staff_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
