# Generated by Django 3.2.15 on 2023-02-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeman', '0010_staffmem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMem',
        ),
    ]
