# Generated by Django 3.2.15 on 2023-01-17 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20230117_0138'),
        ('company', '0002_addressbook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.driver'),
        ),
    ]
