# Generated by Django 3.2.15 on 2023-01-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_addressbook_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='gen_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='vegi_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
