# Generated by Django 3.2.15 on 2023-03-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20230129_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='representative',
            new_name='driver',
        ),
    ]
